import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Courses App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html dir={locale === "en" ? "ltr" : "rtl"} lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
